### ISSUE TITLE
Load Pandas DF into Redshift table

### ISSUE THREAD

**Issue by fdosani** [capitalone/Data-Load-and-Copy-using-Python#16]
This might be some nice functionality which we can build out.
I can see a bunch of people wrangling with Pandas and then wanting to get this into Redshift.

**Comment by dasjyao** [comment]
What are your thoughts on this? We could potentially follow the same idea as `insert_dataframe_to_table()` in Snowflake class.

**Comment by fdosani** [comment]
I think this makes sense. Feel free to work on this if you have some time?

**Comment by dasjyao** [comment]
This has been implemented.
