### ISSUE TITLE
Sphinx is resolving default values in functions

### ISSUE THREAD

**Issue by fdosani** [capitalone/Data-Load-and-Copy-using-Python#36]
Seems like we need a work around for this "bug". Relates to https://github.com/sphinx-doc/sphinx/issues/759
Basically default values in functions get fully resolved and we have things like `local_path=os.getcwd()`

**Comment by theianrobertson** [comment]
I guess we could just make the defaults None, and set in the function

**Comment by fdosani** [comment]
Yup that seems to be a work around for now. 👍
