### ISSUE TITLE
pulling data from RS w/o adding S3 credentials raise an err

### ISSUE THREAD

**Issue by krystinli** [capitalone/Data-Load-and-Copy-using-Python#49]
A question was raised in an internal slack channel about getting `S3CredentialsError` when trying to sample data from RS (not doing any ETL job so doesn't really require S3 credentials). 

The msg I expect to get here would be: `S3 credentials we not found. S3 functionality is disabled`
Not sure if we both set the inputs wrong but want to do some investigation on this.

**Comment by krystinli** [comment]
Confirmed this is a real issue - starting looking into way to fix this. Thanks for confirming @dasjyao

**Comment by krystinli** [comment]
idea for fixing it:
- add `except` condition here: https://github.com/capitalone/Data-Load-and-Copy-using-Python/blob/master/locopy/redshift.py#L153
similar to SF: https://github.com/capitalone/Data-Load-and-Copy-using-Python/blob/master/locopy/snowflake.py#L174

**Comment by fdosani** [comment]
I think this makes sense. Should be a pretty simple and straightforward fix.

**Comment by fdosani** [comment]
Fixed in #57
