### ISSUE TITLE
Support for SQLite3

### ISSUE THREAD

**Issue by ak-gupta** [capitalone/Data-Load-and-Copy-using-Python#50]
I tried to connect to a local SQLite3 database using Locopy and it threw the following error:

```
ValueError: parameters are of unsupported type
```

After doing some digging, it looks like the error is being thrown by the default argument in `locopy.database.Database.execute()` for `params`. Once I started using `params=()`, it started working.

e.g.

```python
with locopy.Database(dbapi=sqlite3, database=':memory:') as cmd:
  cmd.execute('''CREATE TABLE stocks (date text, qty real)''', params=())
```

I tested `params=()` with `locopy.snowflake.Snowflake` as well and it worked.

**Comment by jborchma** [comment]
To be fair, there are already a lot of SQLite packages out there. I wonder if this should be really the scope of locopy.

**Comment by fdosani** [comment]
I'm ok with this if it extends support to other DBAPI 2.0 adapters. I don't think we'd add loading / unloading functionality but just to use the `execute` should be fine especially if it is just tweaking `params`. @ak-gupta Did you want to propose a PR with tests for this?

**Comment by ak-gupta** [comment]
@jborchma Yeah I agree with your point. I guess I was more focused on whether or not the current default `params=None` is correct given that it has no impact on Snowflake queries and it allows users to query SQLite databases.

@fdosani Yes I was thinking the same; it's probably out of the package scope to add a new `Database` subclass. I can work on a PR

**Comment by fdosani** [comment]
@ak-gupta any traction on this feature? No pressure, just wondering if you needed a hand

**Comment by ak-gupta** [comment]
Sorry, I didn't have a chance to work on this until recently. I've made the changes and it looks like the tests are running nicely! I'll submit a PR once I've done another sweep.
