### ISSUE TITLE
`asn1crypto` new release breaks the SF connection

### ISSUE THREAD

**Issue by krystinli** [capitalone/Data-Load-and-Copy-using-Python#53]
The err msg is: 
```
.conda/envs/py37/lib/python3.7/site-packages/asn1crypto/keys.py", line 1065, in unwrap
    'asn1crypto.keys.PublicKeyInfo().unwrap() has been removed, '
asn1crypto._errors.APIException: asn1crypto.keys.PublicKeyInfo().unwrap() has been removed, please use oscrypto.asymmetric.PublicKey
().unwrap() instead
```
which is probably triggered by the [new release](https://github.com/wbond/asn1crypto/releases) by asn1crypto. need to add `asn1crypto==0.24.0` as dependency.

**Comment by fdosani** [comment]
@krystinli we don't actually enforce the SF connector version in locopy. 
In the dev requirements we do pin to `snowflake-connector-python==1.7.6` but ultimately it is up to users to choose. So not a specific locopy issue per say.

**Comment by krystinli** [comment]
I see. Thanks! @fdosani
