### ISSUE TITLE
use snowflake-connector-python's function to export to pandas

### ISSUE THREAD

**Issue by jfyu** [capitalone/Data-Load-and-Copy-using-Python#77]
Snowflake has a new method to efficiently export to `pandas` 
https://docs.snowflake.net/manuals/user-guide/python-connector-pandas.html#

A test with 8463105 rows of data shows a ~20x speed up on Snowflake.

**Comment by fdosani** [comment]
@dasjyao Did you want to take a look at this? It could be helpful and replace our own implementation.

**Comment by dasjyao** [comment]
Looks good! Will do some performance tests before implement the changes.

**Comment by fdosani** [comment]
@dasjyao Have you done any work on this? I might take a stab at it if not.

**Comment by fdosani** [comment]
@jfyu When you ran this test did you run it on the same table back to back? I'm wondering if the efficiency gain you saw was SF caching the results? I'm just testing it out on 779.0K row dataset and I don't really see any gains. It spends most of the time just downloading the data.

**Comment by jfyu** [comment]
@fdosani huh that's a good question. It's been a while since I did the test. Maybe it's SF after all!! I can try to double check this but not this week.  But if that's what you are finding we can de-prio this.

**Comment by dasjyao** [comment]
sorry, I completely forgot about this as it got busy with work earlier. But I remember I did run one test months ago and see some improvements (don't remember exactly how big the difference is). @fdosani Please feel free to work on it If you want. If not, I can pick it up again.

**Comment by fdosani** [comment]
@dasjyao Would you mind running some tests to check performance on your end? I'm still not seeing any really. But it does simplify the code which is a positive.

**Comment by dasjyao** [comment]
for sure! I will do some tests and report back this week.

**Comment by fdosani** [comment]
There is also write methods to put a df back into a table which could help clean up the code a bit.

**Comment by dasjyao** [comment]
I have run 30 tests to pull data from a table with ~70 columns. From the result below, `fetch_pandas_all()` performs about 2-3 times better than `fetchall()` in general. However, The new function seems to have very high requirements for the environment. I always got `Segmentation fault: 11` when i ran this function from local. I'm not sure if it's just me. @fdosani would you mind trying to see if you can reproduce the same error? If that's an issue, I would recommend to have an option to switch back to `fetchall()` in the case when the new function fails. 
```    
      row_size  fetch_all  fetch_pandas
0      1987003  36.692733      9.676616
1       393963   5.751460      2.204298
2      1122777  12.095722      4.905406
3      1299286  14.072498      6.290301
4       897154  10.240554      4.604224
5      1029770  12.795818      7.083390
6      1417679  15.777973      7.162826
7      2829893  30.453512     13.125842
8      1481083  16.416293      7.430757
9      1169218  12.856212      5.335738
10     3043863  32.236692     13.772858
11     1920762  21.132539      9.060583
12     3525649  37.232501     17.885588
13     3800646  40.159850     17.240576
14     3199208  34.441831     24.363943
15     1379850  15.075403      8.692440
16     4786611  49.407794     25.387532
17      606383   7.374214      2.919430
18     2963895  30.957134     13.902957
19     2643807  27.739896     12.139245
20     1800207  19.034973      8.413508
21     4613072  47.879083     22.032341
22     2791168  29.589400     11.921853
23     3509180  36.891674     16.042753
24     1849277  19.943107      8.790991
25     1768059  18.980515      8.491843
26     1101614  12.014528      5.204859
27      300523   3.821525      3.384054
28      700474   7.825704      3.129873
29     2628029  28.370677     12.026310
```

**Comment by fdosani** [comment]
Thanks @dasjyao! That’s interesting are these just back to back test? Again
concerned about the caching within snowflake.  It seems like these are all
different tables with 2 tests each?

**Comment by dasjyao** [comment]
These are tests from sampling different row sizes from the same table. The reason I chose to do that is to test the impact from different table sizes. In addition, in order not to confound with caching within snowflake, I put the `time()` only around `fetch_all()` and `fetch_pandas_all()`. So the time here shows only the time that each function takes, not including the execution part.

**Comment by fdosani** [comment]
Makes sense. Thanks for clarifying! Ok looks like it might make sense to
switch then!
