### ISSUE TITLE
Snowflake's write_pandas() function

### ISSUE THREAD

**Issue by fdosani** [capitalone/Data-Load-and-Copy-using-Python#86]
Just want to have the discussion here vs in the PR.

Proposal: Add a flag `use_write_pandas` to `insert_dataframe_to_table` which will defer to the `write_pandas` method rather than running the `INSERT INTO` statements. This would give ppl both options.

Basically:

```
if use_write_pandas:
   # run self.cur.write_pandas(......)
else:
   insert_query = """INSERT INTO {table_name} {columns} VALUES {values}""".format(
            table_name=table_name, columns=column_sql, values=string_join
        )
``` 

We can keep the table creation / metadata part in this scenario.

Docs: https://docs.snowflake.com/en/user-guide/python-connector-api.html#label-python-connector-api-write-pandas

**Comment by dasjyao** [comment]
I would recommend to replace `insert_query` with `write_pandas()`. This is mainly for two reasons,
1. two functions essentially perform the same task, inserting dataframe to snowflake table. From users' stand point, they would always choose `write_pandas()` over `insert_query` if the former outperforms the latter. 
2. `insert_query` has a limitation of dataframe size for each insertion, but `write_pandas` bypasses this problem.

Based on the performance test, `write_pandas` is about ~10X faster than `insert_query`

My proposed change will be below:
```
def insert_dataframe_to_table(self, df, table_name, create=False ...):
      if create:
            create_table()
      write_pandas(self.conn, df, table_name)
```

**Comment by fdosani** [comment]
Yeah this is certainly something else we should consider. My thought was to
allow ppl to have both. I think for some small datasets the copy would be
less performant.

I’m easy either way but maybe we should run some tests from small to large
datasets?

**Comment by dasjyao** [comment]
@fdosani I can help with some tests from small to large datasets and share some results later.

**Comment by dasjyao** [comment]
I have tested both functions on different table sizes (each size has 20 iterations, table has ~70 columns). The performance of `write_pandas` increases exponentially with the increase of table size. `insert` only marginally performs better while table is small.  Based on the test result, I would still vote for replacement other than adding a flag.

```
row_size  insert.  write_pandas
10000     29.76     3.56
1000      4.52      3.15
100      2.4       3.23
```

Any thoughts?

**Comment by fdosani** [comment]
Thanks for the analysis here! Nice work. I’m on-board with replacing.
Anyone else have any thoughts on this?

**Comment by theianrobertson** [comment]
👋

Makes sense to replace, unless there's any downsides to `write_pandas` (there's no credentials neede or anything is there?)

**Comment by fdosani** [comment]
👋 OK I think we can move forward with that change then.

**Comment by dasjyao** [comment]
@fdosani 
I just realize there's one important use case to keep `insert` statements. It's the case when user wants to insert only a subset of the table. I don't think `write_pandas` has that option to insert only a part of the table.

**Comment by fdosani** [comment]
@dasjyao Makes sense. Just to share with others, I feel like the function is a bit unstable at the moment. Even inserting a simple items is causing issues.

**Comment by dasjyao** [comment]
> @fdosani
> I just realize there's one important use case to keep `insert` statements. It's the case when user wants to insert only a subset of the table. I don't think `write_pandas` has that option to insert only a part of the table.

nvm, this is not an issue. I just tested and `write_pandas` can do partial table insert.

**Comment by fdosani** [comment]
@dasjyao Not sure if you tried loading timestamps with `write_pandas`

So the following DF:

```python
pd.DataFrame(
    {
        "a": [1, 2],
        "b": [pd.Timestamp("2013-01-01"), pd.Timestamp("2019-01-01")],
        "c": ["1.2", "3.5"],
        "d": [Decimal(2), Decimal(3)],
    }
)
```

leads to a table like so:

```
ColumnsData Type
A	NUMBER(38,0)
B	TIMESTAMP_NTZ(9)
C	FLOAT
D	FLOAT
```

With the following data for the timestamps:

```
44971-07-26 19:00:00.000
50970-04-27 19:00:00.000
```

Can you get timestamps working on your end? Nothing seems to really work via `write_pandas`
Inserting directly like this works fine: `insert into ...... values('2013-01-01 00:00:00');`

**Comment by fdosani** [comment]
@dasjyao @jborchma @theianrobertson I'm going to close this issue for now. It feel given the issues we've documented I'm not comfortable adding this in for now. I'd like to cut a new release today or tomorrow. We can circle back to this at a later time.

**Comment by dasjyao** [comment]
sounds good to me!
