### ISSUE TITLE
Data loss when splitting csv files with load_and_copy

### ISSUE THREAD

**Issue by daniilmaltsev** [capitalone/Data-Load-and-Copy-using-Python#87]
Python 3.7.3
locopy==0.3.6

When locopy.Redshift().load_and_copy() is called with both **splits=N** and **copy_options=["IGNOREHEADER AS 1"]** arguments,
N-1 data rows are lost,
because load_and_copy function doesn't recreate the csv file's header in the chunks, so the first chunk still has the header, and is copied correctly, while the rest of the chunks' first rows are ignored because of copy_options=["IGNOREHEADER AS 1"].

There's a workaround: remove the csv file's header and call load_and_copy()  without copy_options=["IGNOREHEADER AS 1"].

**Comment by fdosani** [comment]
@daniilmaltsev Thank you for opening the issue. I'll take a look at this a bit later today. Sorry many meetings today. Appreciate you finding this issue and reporting it back.
