### ISSUE TITLE
Any one know how to update multiple rows to a snowflake table from python (preferably pandas). Has data around 1 lakh records that needs to be updated to snowflake tables

### ISSUE THREAD

**Issue by viswan29** [capitalone/Data-Load-and-Copy-using-Python#97]

**Comment by fdosani** [comment]
Couple of questions:

- What is 1 lakh?
- If you are looking to update rows you'll need to generate update statements. `locopy` is more for uploading and downloading data in bulk, not exactly updating.

**Comment by viswan29** [comment]
Hi Faisal, 

1 Lakh records are there for me to update records in snowflake.
I have tried normal query update in python but is updating 50 records per minute in my case to update 100K records, it will run for around 30 hours which is not at all good. So need expertise how can i bulk upload from a dataframe to snowflake table. In my case, i cant use dataframe.to_csv() function because i do not have permission to drop and recreate table.

**Comment by fdosani** [comment]
I'm not sure I know what a lakh is? Is this some number or unit?

This doesn't seem like a locopy issue so I'm going to close the issue. If you need help with snowflake in general please reach out to snowflake support or some other forms. A simple google search yields this: https://community.snowflake.com/s/question/0D50Z00008qDkV8SAK/efficient-way-to-do-update-on-large-table-9-million-rows

**Comment by razorsharpshady** [comment]
@fdosani 1 Lakh = 100k = 100,000
